import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Clock3, FileWarning, Gavel, History, Loader2, ShieldAlert, UserRoundX } from 'lucide-react';
import { Header } from '../components/layout/header-bar';
import { ChatUser } from '../components/chat/chat-box';
import { moderationService, ModerationAction, ModerationLog, ModerationReport } from '../services/moderationService';
import { useToast } from '../context/ToastContext';

interface ModeratorPageProps { activeNavTab: string; setActiveNavTab: (tab: string) => void; onNavigateSettings: () => void; onNavigateProfile: (uid?: string) => void; onNavigateAuth: () => void; activeChatUser: ChatUser | null; setActiveChatUser: (user: ChatUser | null) => void; }

const reasonLabel: Record<string, string> = { SPAM: 'Spam', HATE_SPEECH: 'Ngôn từ thù ghét', HARASSMENT: 'Quấy rối', VIOLENCE: 'Bạo lực', NUDITY: 'Nội dung nhạy cảm', FALSE_INFORMATION: 'Thông tin sai lệch', OTHER: 'Khác' };
const actionLabel: Record<ModerationAction, string> = { DELETE_POST: 'Gỡ bài viết', DELETE_COMMENT: 'Gỡ bình luận', WARN_USER: 'Cảnh cáo người dùng', LOCK_USER: 'Đề xuất khóa tài khoản', DISMISS: 'Bỏ qua báo cáo' };

export const ModeratorPage: React.FC<ModeratorPageProps> = (props) => {
  const [tab, setTab] = useState<'queue' | 'ai' | 'history'>('queue');
  const [reports, setReports] = useState<ModerationReport[]>([]);
  const [logs, setLogs] = useState<ModerationLog[]>([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<ModerationReport | null>(null);
  const [note, setNote] = useState('');
  const [processing, setProcessing] = useState(false);
  const toast = useToast();
  const load = async () => { try { setLoading(true); const [nextReports, nextLogs] = await Promise.all([moderationService.getReports(), moderationService.getLogs()]); setReports(nextReports); setLogs(nextLogs); } catch { toast.showError('Không tải được dữ liệu kiểm duyệt.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const pending = useMemo(() => reports.filter((report) => report.status === 'PENDING' || report.status === 'REVIEWING'), [reports]);
  const aiFlagged = useMemo(() => reports.filter((report) => report.status === 'REVIEWING'), [reports]);
  const process = async (action: ModerationAction) => { if (!selected) return; try { setProcessing(true); await moderationService.processReport(selected.reportId, action, note.trim()); toast.showSuccess(`Đã xử lý: ${actionLabel[action]}.`); setSelected(null); setNote(''); await load(); } catch { toast.showError('Không thể xử lý báo cáo.'); } finally { setProcessing(false); } };
  const visibleReports = tab === 'queue' ? pending : aiFlagged;
  return <div className="min-h-screen bg-[#f0f2f5] dark:bg-[#18191a] text-gray-900 dark:text-[#e4e6eb]"><Header activeTab={props.activeNavTab} onTabChange={props.setActiveNavTab} onNavigateSettings={props.onNavigateSettings} onNavigateProfile={props.onNavigateProfile} onNavigateAuth={props.onNavigateAuth} onSelectChatUser={props.setActiveChatUser} />
    <main className="mx-auto max-w-7xl px-4 pt-20 pb-10"><div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#1877f2]">Safety Center</p><h1 className="text-3xl font-extrabold">Trung tâm kiểm duyệt</h1><p className="mt-1 text-sm text-gray-500">Xem xét báo cáo, xử lý nội dung vi phạm và theo dõi lịch sử quyết định.</p></div><button onClick={load} className="rounded-xl bg-white dark:bg-[#242526] px-4 py-2 text-sm font-bold shadow">Làm mới</button></div>
      <div className="grid gap-4 sm:grid-cols-3 mb-6"><Stat icon={<Clock3 />} label="Chờ xử lý" value={pending.length} tone="amber" /><Stat icon={<ShieldAlert />} label="AI cần xem xét" value={aiFlagged.length} tone="rose" /><Stat icon={<History />} label="Đã xử lý" value={logs.length} tone="blue" /></div>
      <div className="mb-4 flex gap-2 border-b border-gray-200 dark:border-[#393a3b]"><Tab active={tab === 'queue'} onClick={() => setTab('queue')} label="Hàng chờ báo cáo" /><Tab active={tab === 'ai'} onClick={() => setTab('ai')} label="AI gắn cờ" /><Tab active={tab === 'history'} onClick={() => setTab('history')} label="Lịch sử xử lý" /></div>
      {loading ? <div className="py-20 text-center"><Loader2 className="mx-auto h-8 w-8 animate-spin text-[#1877f2]" /></div> : tab === 'history' ? <Logs logs={logs} /> : <Reports reports={visibleReports} onSelect={(report) => { setSelected(report); setNote(''); }} empty={tab === 'ai' ? 'Chưa có nội dung AI gắn cờ cần xem xét.' : 'Không còn báo cáo nào cần xử lý.'} />}
    </main>{selected && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl dark:bg-[#242526]"><div className="flex items-center gap-2"><Gavel className="h-5 w-5 text-[#1877f2]" /><h2 className="text-lg font-bold">Xử lý báo cáo</h2></div><div className="mt-4 rounded-xl bg-gray-50 p-3 text-sm dark:bg-[#3a3b3c]"><b>{selected.targetType}</b> · {reasonLabel[selected.reason] || selected.reason}<p className="mt-1 text-gray-500">{selected.description || 'Không có mô tả bổ sung.'}</p></div><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Ghi chú gửi vào lịch sử xử lý…" rows={3} className="mt-4 w-full rounded-xl border border-gray-200 bg-gray-50 p-3 text-sm dark:border-[#393a3b] dark:bg-[#3a3b3c]" /><div className="mt-4 flex flex-wrap gap-2"><Action onClick={() => process('DELETE_POST')} disabled={processing || selected.targetType !== 'POST'} label="Gỡ nội dung" danger /><Action onClick={() => process('WARN_USER')} disabled={processing} label="Cảnh cáo" /><Action onClick={() => process('LOCK_USER')} disabled={processing} label="Đề xuất khóa" /><Action onClick={() => process('DISMISS')} disabled={processing} label="Bỏ qua" /><button onClick={() => setSelected(null)} disabled={processing} className="ml-auto px-3 py-2 text-sm font-bold text-gray-500">Đóng</button></div></div></div>}</div>;
};
const Stat = ({ icon, label, value, tone }: any) => <div className="rounded-2xl bg-white p-4 shadow-sm dark:bg-[#242526]"><div className={`mb-2 w-fit rounded-xl p-2 ${tone === 'rose' ? 'bg-rose-50 text-rose-600' : tone === 'amber' ? 'bg-amber-50 text-amber-600' : 'bg-blue-50 text-[#1877f2]'}`}>{React.cloneElement(icon, { className: 'w-5 h-5' })}</div><p className="text-2xl font-extrabold">{value}</p><p className="text-xs text-gray-500">{label}</p></div>;
const Tab = ({ active, onClick, label }: any) => <button onClick={onClick} className={`px-4 py-3 text-sm font-bold ${active ? 'border-b-2 border-[#1877f2] text-[#1877f2]' : 'text-gray-500'}`}>{label}</button>;
const Action = ({ onClick, disabled, label, danger = false }: any) => <button onClick={onClick} disabled={disabled} className={`rounded-xl px-3 py-2 text-xs font-bold disabled:opacity-50 ${danger ? 'bg-red-600 text-white' : 'bg-gray-100 text-gray-700 dark:bg-[#3a3b3c] dark:text-white'}`}>{label}</button>;
const Reports = ({ reports, onSelect, empty }: { reports: ModerationReport[]; onSelect: (report: ModerationReport) => void; empty: string }) => reports.length === 0 ? <div className="rounded-2xl bg-white py-16 text-center shadow-sm dark:bg-[#242526]"><CheckCircle2 className="mx-auto mb-3 h-10 w-10 text-emerald-500" /><p className="font-bold">{empty}</p></div> : <div className="space-y-3">{reports.map((report) => <button key={report.reportId} onClick={() => onSelect(report)} className="w-full rounded-2xl bg-white p-4 text-left shadow-sm transition hover:shadow-md dark:bg-[#242526]"><div className="flex gap-3"><div className="rounded-xl bg-rose-50 p-2 text-rose-600"><AlertTriangle className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><p className="font-bold">{report.targetType} · {reasonLabel[report.reason] || report.reason}</p><span className="rounded-full bg-amber-50 px-2 py-1 text-[11px] font-bold text-amber-700">{report.status}</span></div><p className="mt-1 truncate text-sm text-gray-500">{report.description || 'Không có mô tả bổ sung.'}</p><p className="mt-2 text-xs text-gray-400">{new Date(report.createdAt).toLocaleString('vi-VN')} · Mã: {report.targetId}</p></div></div></button>)}</div>;
const Logs = ({ logs }: { logs: ModerationLog[] }) => logs.length === 0 ? <div className="rounded-2xl bg-white py-16 text-center shadow-sm dark:bg-[#242526]"><FileWarning className="mx-auto mb-3 h-10 w-10 text-gray-400" /><p className="font-bold">Chưa có lịch sử xử lý.</p></div> : <div className="space-y-3">{logs.map((log) => <div key={log.logId} className="rounded-2xl bg-white p-4 shadow-sm dark:bg-[#242526]"><p className="font-bold">{actionLabel[log.action]}</p><p className="mt-1 text-sm text-gray-500">{log.note || log.reason || 'Không có ghi chú.'}</p><p className="mt-2 text-xs text-gray-400">{log.targetType} · {log.targetId} · {new Date(log.createdAt).toLocaleString('vi-VN')}</p></div>)}</div>;
