import React, { useEffect, useState } from 'react';
import { CheckCircle2, FileWarning, Loader2, RotateCcw } from 'lucide-react';
import { Header } from '../components/layout/header-bar';
import { ChatUser } from '../components/chat/chat-box';
import { reportService, SubmittedReport } from '../services/reportService';
import { useToast } from '../context/ToastContext';

interface Props { activeNavTab: string; setActiveNavTab: (tab: string) => void; onNavigateSettings: () => void; onNavigateProfile: (uid?: string) => void; onNavigateAuth: () => void; activeChatUser: ChatUser | null; setActiveChatUser: (user: ChatUser | null) => void; }
const labels: Record<string, string> = { PENDING: 'Đang chờ', REVIEWING: 'Đang xem xét', RESOLVED: 'Đã xử lý', DISMISSED: 'Không vi phạm' };

export const SupportInboxPage: React.FC<Props> = (props) => {
  const [reports, setReports] = useState<SubmittedReport[]>([]); const [loading, setLoading] = useState(true); const [appealId, setAppealId] = useState<string | null>(null); const [message, setMessage] = useState(''); const toast = useToast();
  const load = async () => { try { setLoading(true); setReports(await reportService.getMyReports()); } catch { toast.showError('Không tải được Hộp thư hỗ trợ.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const appeal = async () => { if (!appealId || !message.trim()) return; try { await reportService.appeal(appealId, message.trim()); toast.showSuccess('Đã gửi yêu cầu xem xét lại.'); setAppealId(null); setMessage(''); load(); } catch { toast.showError('Không thể gửi yêu cầu xem xét lại.'); } };
  return <div className="min-h-screen bg-[#f0f2f5] text-gray-900 dark:bg-[#18191a] dark:text-[#e4e6eb]"><Header activeTab={props.activeNavTab} onTabChange={props.setActiveNavTab} onNavigateSettings={props.onNavigateSettings} onNavigateProfile={props.onNavigateProfile} onNavigateAuth={props.onNavigateAuth} onSelectChatUser={props.setActiveChatUser} /><main className="mx-auto max-w-3xl px-4 pb-10 pt-20"><p className="text-xs font-bold uppercase tracking-wider text-[#1877f2]">Support Inbox</p><h1 className="mt-1 text-3xl font-extrabold">Báo cáo của bạn</h1><p className="mt-1 text-sm text-gray-500">Theo dõi quyết định kiểm duyệt và yêu cầu xem xét lại khi cần.</p>{loading ? <Loader2 className="mx-auto mt-16 animate-spin text-[#1877f2]" /> : reports.length === 0 ? <div className="mt-6 rounded-2xl bg-white py-16 text-center shadow-sm dark:bg-[#242526]"><CheckCircle2 className="mx-auto mb-3 text-emerald-500" /><b>Bạn chưa gửi báo cáo nào.</b></div> : <div className="mt-6 space-y-3">{reports.map(r => <div key={r.reportId} className="rounded-2xl bg-white p-4 shadow-sm dark:bg-[#242526]"><div className="flex justify-between gap-3"><div><b>{r.targetType} · {r.reason}</b><p className="mt-1 text-sm text-gray-500">{r.description || 'Không có mô tả bổ sung.'}</p></div><span className="h-fit rounded-full bg-blue-50 px-2 py-1 text-xs font-bold text-blue-700">{labels[r.status] || r.status}</span></div><p className="mt-3 text-xs text-gray-400">Gửi lúc {new Date(r.createdAt).toLocaleString('vi-VN')}</p>{(r.status === 'RESOLVED' || r.status === 'DISMISSED') && <button onClick={() => setAppealId(r.reportId)} className="mt-3 flex items-center gap-1 text-sm font-bold text-[#1877f2]"><RotateCcw className="h-4 w-4" />Yêu cầu xem xét lại</button>}</div>)}</div>}{appealId && <div className="fixed inset-0 z-[100] grid place-items-center bg-black/60 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-5 dark:bg-[#242526]"><h2 className="font-extrabold">Yêu cầu xem xét lại</h2><textarea value={message} onChange={e => setMessage(e.target.value)} placeholder="Nêu lý do bạn cần xem xét lại…" className="mt-3 w-full rounded-xl border p-3 text-sm dark:bg-[#3a3b3c]" rows={4} /><div className="mt-3 flex justify-end gap-2"><button onClick={() => setAppealId(null)} className="px-3 py-2 text-sm font-bold">Hủy</button><button disabled={!message.trim()} onClick={appeal} className="rounded-xl bg-[#1877f2] px-3 py-2 text-sm font-bold text-white disabled:opacity-50">Gửi yêu cầu</button></div></div></div>}</main></div>;
};
