import { useEffect, useState } from 'react';
import { Clock3, Trash2 } from 'lucide-react';
import { CreatePostBox } from '../post/CreatePostBox';
import { PostCard } from '../post/post-card';
import { GroupData } from './GroupBanner';
import { GroupRemovePostModal } from './GroupRemovePostModal';
import { postService } from '../../services/api';
import { Post } from '../../types';

export const GroupDiscussionTab = ({ group }: { group: GroupData }) => {
  const [posts, setPosts] = useState<Post[]>([]); const [loading, setLoading] = useState(true); const [submissionMessage, setSubmissionMessage] = useState(''); const [removingId, setRemovingId] = useState<string | null>(null); const [postToRemove, setPostToRemove] = useState<Post | null>(null);
  const canModerate = Boolean(group.isAdmin || group.isModerator);
  useEffect(() => { if (!group.id) return; setLoading(true); postService.getGroupPosts(group.id).then(setPosts).catch(() => setPosts([])).finally(() => setLoading(false)); }, [group.id]);
  const remove = async (reason: string) => { if (!postToRemove) return; try { setRemovingId(postToRemove.id); await postService.removeGroupPost(postToRemove.id, reason || undefined); setPosts((items) => items.filter((item) => item.id !== postToRemove.id)); setPostToRemove(null); } finally { setRemovingId(null); } };
  return <><div className="flex w-full gap-4"><div className="max-w-[680px] flex-1">{group.isMember && <div className="mb-4"><CreatePostBox onPostCreated={(post) => { if (post.status === 'PENDING_APPROVAL') setSubmissionMessage('Bài viết đã được gửi và đang chờ kiểm duyệt.'); else setPosts((current) => [post, ...current]); }} groupId={group.id} /></div>}{submissionMessage && <div className="mb-4 flex items-center gap-2 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800 dark:border-amber-700/50 dark:bg-amber-900/20 dark:text-amber-100"><Clock3 className="h-4 w-4 shrink-0" />{submissionMessage}</div>}{loading ? <div className="rounded-2xl bg-white p-8 text-center text-sm text-gray-500 shadow dark:bg-[#242526]">Đang tải bài viết...</div> : posts.length === 0 ? <div className="mt-4 rounded-2xl bg-white p-8 text-center shadow dark:bg-[#242526]"><p className="text-gray-500 dark:text-[#b0b3b8]">Chưa có bài viết nào đã được duyệt trong nhóm này.</p></div> : posts.map((post) => <div key={post.id} className="relative mb-4">{canModerate && <div className="absolute right-3 top-3 z-10"><button disabled={removingId === post.id} onClick={() => setPostToRemove(post)} className="inline-flex items-center gap-1 rounded-lg bg-red-600 px-3 py-2 text-xs font-bold text-white shadow hover:bg-red-700 disabled:opacity-60"><Trash2 className="h-4 w-4" />Gỡ bài</button></div>}<PostCard post={post} onDeletePost={(id) => setPosts((current) => current.filter((item) => item.id !== id))} /></div>)}</div><div className="hidden w-[300px] lg:block"><div className="sticky top-20 rounded-2xl bg-white p-4 shadow dark:bg-[#242526]"><h3 className="mb-2 font-bold text-gray-900 dark:text-[#e4e6eb]">Giới thiệu</h3><p className="text-sm text-gray-600 dark:text-[#b0b3b8]">{group.description || 'Cùng chia sẻ, trao đổi và kết nối trong cộng đồng này.'}</p>{group.rules && <><h4 className="mb-2 mt-4 font-bold text-gray-900 dark:text-[#e4e6eb]">Nội quy nhóm</h4><p className="whitespace-pre-line text-sm text-gray-600 dark:text-[#b0b3b8]">{group.rules}</p></>}{group.postApprovalRequired && <p className="mt-4 rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-700 dark:bg-amber-900/20 dark:text-amber-200">Bài viết trong nhóm cần được quản trị viên duyệt trước khi hiển thị.</p>}</div></div></div><GroupRemovePostModal post={postToRemove} loading={removingId === postToRemove?.id} onClose={() => setPostToRemove(null)} onConfirm={(reason) => void remove(reason)} /></>;
};
