import { useEffect, useState } from 'react';
import { Check, Loader2, RotateCcw, X } from 'lucide-react';
import { GroupResponse } from '../../services/groupService';
import { postService } from '../../services/api';

export const GroupAppealsTab = ({ group }: { group: GroupResponse }) => {
  const canReview = Boolean(group.isAdmin || group.isModerator); const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState<any | null>(null); const [message, setMessage] = useState('');
  const load = async () => { try { setLoading(true); setItems(canReview ? await postService.getGroupAppeals(group.id) : await postService.getMyGroupAppeals(group.id)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [group.id, canReview]);
  const submit = async () => { if (!selected || !message.trim()) return; await postService.appealGroupPost(selected.postId, message.trim()); setSelected(null); setMessage(''); await load(); };
  const review = async (id: string, approved: boolean) => { await postService.reviewGroupAppeal(id, approved); await load(); };
  return <div className="w-full max-w-[760px]"><div className="mb-4 rounded-2xl bg-white p-5 shadow dark:bg-[#242526]"><h2 className="text-xl font-extrabold">{canReview ? 'Kháng nghị chờ xử lý' : 'Kháng nghị bài viết trong nhóm'}</h2></div>{loading ? <Loader2 className="mx-auto mt-10 animate-spin text-[#1877f2]" /> : items.length === 0 ? <div className="rounded-2xl bg-white p-10 text-center text-sm text-gray-500 shadow dark:bg-[#242526]">{canReview ? 'Không có kháng nghị đang chờ.' : 'Bạn chưa có bài viết bị gỡ trong nhóm.'}</div> : <div className="space-y-4">{items.map((item) => <article key={item.postId} className="rounded-2xl bg-white p-5 shadow dark:bg-[#242526]"><b>{canReview ? 'Bài viết cần xem xét' : 'Bài viết đã bị gỡ'}</b><p className="mt-2 whitespace-pre-wrap text-sm">{item.content || 'Bài viết không có nội dung chữ.'}</p><p className="mt-3 text-sm text-red-500">Lý do gỡ: {item.reason}</p>{canReview ? <><div className="mt-3 rounded-xl bg-blue-50 p-3 text-sm dark:bg-blue-900/20"><b>Lý do kháng nghị:</b><p className="mt-1">{item.appealMessage}</p></div><div className="mt-4 flex gap-2"><button onClick={() => void review(item.postId, true)} className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-2 text-sm font-bold text-white"><Check size={16} />Chấp nhận & khôi phục</button><button onClick={() => void review(item.postId, false)} className="inline-flex items-center gap-1 rounded-lg bg-red-600 px-3 py-2 text-sm font-bold text-white"><X size={16} />Bác bỏ</button></div></> : <>{item.appealStatus ? <p className="mt-3 text-sm font-bold text-amber-600">{item.appealStatus === 'PENDING' ? 'Đang chờ xử lý' : item.appealStatus === 'ACCEPTED' ? 'Đã chấp nhận' : 'Đã bác bỏ'}</p> : <button onClick={() => { setSelected(item); setMessage(''); }} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-[#1877f2] px-3 py-2 text-sm font-bold text-white"><RotateCcw size={16} />Kháng nghị</button>}</>}</article>)}</div>}{selected && <div className="fixed inset-0 z-[100] grid place-items-center bg-black/60 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-5 dark:bg-[#242526]"><h3 className="font-extrabold">Gửi kháng nghị trong nhóm</h3><textarea value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Nêu lý do kháng nghị..." className="mt-3 w-full rounded-xl border p-3 dark:bg-[#3a3b3c]" rows={4} /><div className="mt-3 flex justify-end gap-2"><button onClick={() => setSelected(null)} className="px-3 py-2 font-bold">Hủy</button><button disabled={!message.trim()} onClick={() => void submit()} className="rounded-lg bg-[#1877f2] px-3 py-2 font-bold text-white">Gửi kháng nghị</button></div></div></div>}</div>;
};
